# Generated by Django 2.1.2 on 2018-10-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='Movies', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='country',
            field=models.CharField(default='UY', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='email',
            field=models.EmailField(default='def@ul.t', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='phone',
            field=models.IntegerField(default=12345678),
            preserve_default=False,
        ),
    ]
